language: c++
install:
 - sudo apt-get update -qq
 - sudo apt-get install -y qt4-qmake libqt4-dev xvfb

script:  
 - mkdir -p build 
 - cd build 
 - qmake ../qt-info.pro 
 - make
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - ./qt-info
